"""첨부 — 무엇에 붙었는지는 문자열 두 칸으로 든다.

도메인마다 첨부 표를 따로 만들면 업로드·내려받기·권한 판정이 그 수만큼 갈라진다.
그렇다고 공통 틀이 도메인 표에 외래키를 걸 수도 없다 — 그러면 포크한 플랫폼이
없는 표를 가리킨다. 그래서 `owner_table` + `owner_id` 로 **느슨하게** 가리킨다.

`workspace_id` 는 RESTRICT 다. 부서를 지울 때 첨부가 조용히 사라지면 안 되고,
부서 삭제 확인 화면이 그 수를 먼저 보여 준다.

Revision ID: 0002_attachments
Revises: 0001_initial
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0002_attachments"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_table", sa.String(length=60), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("relative_path", sa.String(length=300), nullable=False),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_attachments_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_attachments_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    op.create_index(
        op.f("ix_attachments_created_at"), "attachments", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_attachments_deleted_at"), "attachments", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_attachments_owner_id"), "attachments", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_attachments_owner_table"), "attachments", ["owner_table"], unique=False
    )
    op.create_index(op.f("ix_attachments_sha256"), "attachments", ["sha256"], unique=False)
    op.create_index(
        op.f("ix_attachments_workspace_id"), "attachments", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attachments_workspace_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_sha256"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_owner_table"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_owner_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_deleted_at"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_created_at"), table_name="attachments")
    op.drop_table("attachments")
    # ### end Alembic commands ###
