"""온톨로지 메타모델 — 그룹·타입·속성정의·객체

도메인을 코드가 아니라 데이터로 정의하기 위한 첫 표들(ADR 0005).

**행은 여기 넣지 않는다.** 첫 그룹·타입은 설치 시드(`scripts/seed_install.py`)가
심는다 — 마이그레이션에 넣으면 모델로 표를 만드는 시험이 그 행을 못 받아,
같은 목록을 시험 쪽에 한 벌 더 적게 된다.

Revision ID: 0003_ontology
Revises: 0002_attachments
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0003_ontology"
down_revision = "0002_attachments"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nav_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("icon", sa.String(length=40), server_default="", nullable=False),
        sa.Column("audience", sa.String(length=20), server_default="everyone", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nav_groups")),
        sa.UniqueConstraint("slug", name="uq_nav_groups_slug"),
    )
    op.create_table(
        "property_defs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_kind", sa.String(length=20), server_default="type", nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=48), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("data_type", sa.String(length=20), nullable=False),
        sa.Column("unit", sa.String(length=24), server_default="", nullable=False),
        sa.Column("help", sa.String(length=200), server_default="", nullable=False),
        sa.Column("required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("multi", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("enum_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ref_type_slug", sa.String(length=32), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_defs")),
        sa.UniqueConstraint(
            "owner_kind", "owner_id", "key", name="uq_property_defs_owner_key"
        ),
    )
    op.create_index(
        op.f("ix_property_defs_owner_id"), "property_defs", ["owner_id"], unique=False
    )
    op.create_table(
        "object_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("icon", sa.String(length=40), server_default="", nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("nav_group_id", sa.UUID(), nullable=True),
        sa.Column("kind_class", sa.String(length=20), server_default="record", nullable=False),
        sa.Column("entry_policy", sa.String(length=20), server_default="open", nullable=False),
        sa.Column("key_policy", sa.String(length=20), server_default="none", nullable=False),
        sa.Column("key_scope", sa.String(length=20), server_default="global", nullable=False),
        sa.Column(
            "temporal_kind", sa.String(length=20), server_default="evergreen", nullable=False
        ),
        sa.Column(
            "list_view",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nav_group_id"],
            ["nav_groups.id"],
            name=op.f("fk_object_types_nav_group_id_nav_groups"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_object_types")),
        sa.UniqueConstraint("slug", name="uq_object_types_slug"),
    )
    op.create_table(
        "objects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("owner_workspace_id", sa.UUID(), nullable=True),
        sa.Column("valid_from_year", sa.Integer(), nullable=True),
        sa.Column("valid_to_year", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_objects_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_objects_owner_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["object_types.id"],
            name=op.f("fk_objects_type_id_object_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_objects")),
    )
    op.create_index(op.f("ix_objects_deleted_at"), "objects", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_objects_label"), "objects", ["label"], unique=False)
    op.create_index(
        op.f("ix_objects_owner_workspace_id"), "objects", ["owner_workspace_id"], unique=False
    )
    op.create_index(
        "ix_objects_properties",
        "objects",
        ["properties"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_objects_type_id"), "objects", ["type_id"], unique=False)
    op.create_index("ix_objects_type_status", "objects", ["type_id", "status"], unique=False)
    op.add_column("attachments", sa.Column("owner_field", sa.String(length=48), nullable=True))
    op.create_index(
        op.f("ix_attachments_owner_field"), "attachments", ["owner_field"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attachments_owner_field"), table_name="attachments")
    op.drop_column("attachments", "owner_field")
    op.drop_index("ix_objects_type_status", table_name="objects")
    op.drop_index(op.f("ix_objects_type_id"), table_name="objects")
    op.drop_index("ix_objects_properties", table_name="objects", postgresql_using="gin")
    op.drop_index(op.f("ix_objects_owner_workspace_id"), table_name="objects")
    op.drop_index(op.f("ix_objects_label"), table_name="objects")
    op.drop_index(op.f("ix_objects_deleted_at"), table_name="objects")
    op.drop_table("objects")
    op.drop_table("object_types")
    op.drop_index(op.f("ix_property_defs_owner_id"), table_name="property_defs")
    op.drop_table("property_defs")
    op.drop_table("nav_groups")
    # ### end Alembic commands ###
