"""관계 종류 · 뷰와 묶음 칸

2-a 의 `relation_types` 와, **2-f 의 「나중에 넣으면 아픈 칸」** 넷을 함께 넣는다
(`object_types.form_view`·`detail_view`·`title_template`, `property_defs.section`).
동작은 3단계지만 칸을 지금 두는 이유는 시간 차원 칸을 1단계에 둔 것과 같다 —
나중에 더하면 그때는 데이터가 이미 쌓여 있다.

**행은 여기 넣지 않는다.** 시작 관계 세트가 필요하면 설치 시드가 심는다.

Revision ID: 0004_relation_types
Revises: 0003_ontology
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0004_relation_types"
down_revision = "0003_ontology"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "relation_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("inverse_label", sa.String(length=64), server_default="", nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("directed", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("transitive", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("acyclic", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "cardinality", sa.String(length=20), server_default="many_to_many", nullable=False
        ),
        sa.Column("src_type_slugs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dst_type_slugs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relation_types")),
        sa.UniqueConstraint("slug", name="uq_relation_types_slug"),
    )
    op.add_column(
        "object_types",
        sa.Column(
            "form_view",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "object_types",
        sa.Column(
            "detail_view",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "object_types",
        sa.Column("title_template", sa.String(length=200), server_default="", nullable=False),
    )
    op.add_column(
        "property_defs",
        sa.Column("section", sa.String(length=48), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("property_defs", "section")
    op.drop_column("object_types", "title_template")
    op.drop_column("object_types", "detail_view")
    op.drop_column("object_types", "form_view")
    op.drop_table("relation_types")
    # ### end Alembic commands ###
