"""객체 관계 — 엣지 한 표

관계 종류(`relation_types`)에 **FK 를 걸지 않는다.** 종류의 추가·삭제가
마이그레이션이 아니라 설정 변경이어야 하기 때문이다 — 도메인을 데이터로
정의한다는 이 설계의 전제가 그것이다.

Revision ID: 0005_object_relations
Revises: 0004_relation_types
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0005_object_relations"
down_revision = "0004_relation_types"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "object_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("src_object_id", sa.UUID(), nullable=False),
        sa.Column("dst_object_id", sa.UUID(), nullable=False),
        sa.Column("relation", sa.String(length=32), nullable=False),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("evidence_note", sa.String(length=500), server_default="", nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_object_relations_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["dst_object_id"],
            ["objects.id"],
            name=op.f("fk_object_relations_dst_object_id_objects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["src_object_id"],
            ["objects.id"],
            name=op.f("fk_object_relations_src_object_id_objects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_object_relations")),
        sa.UniqueConstraint(
            "src_object_id", "dst_object_id", "relation", name="uq_object_relations_edge"
        ),
    )
    op.create_index(
        "ix_object_relations_dst",
        "object_relations",
        ["dst_object_id", "relation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_object_relations_dst_object_id"),
        "object_relations",
        ["dst_object_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_object_relations_relation"), "object_relations", ["relation"], unique=False
    )
    op.create_index(
        "ix_object_relations_src",
        "object_relations",
        ["src_object_id", "relation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_object_relations_src_object_id"),
        "object_relations",
        ["src_object_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_object_relations_src_object_id"), table_name="object_relations")
    op.drop_index("ix_object_relations_src", table_name="object_relations")
    op.drop_index(op.f("ix_object_relations_relation"), table_name="object_relations")
    op.drop_index(op.f("ix_object_relations_dst_object_id"), table_name="object_relations")
    op.drop_index("ix_object_relations_dst", table_name="object_relations")
    op.drop_table("object_relations")
    # ### end Alembic commands ###
