"""연도 배정 — `temporal_kind='yearly'` 인 축

모델명처럼 **연도가 불연속인** 값을 위한 표다. 구간(valid_from~valid_to)으로는
2024·2026 에는 쓰고 2025 에는 안 쓰는 것을 표현할 수 없다.

Revision ID: 0006_object_years
Revises: 0005_object_relations
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0006_object_years"
down_revision = "0005_object_relations"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "object_years",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["objects.id"],
            name=op.f("fk_object_years_object_id_objects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_object_years")),
        sa.UniqueConstraint("object_id", "year", name="uq_object_years_object_year"),
    )
    op.create_index(
        op.f("ix_object_years_object_id"), "object_years", ["object_id"], unique=False
    )
    op.create_index(op.f("ix_object_years_year"), "object_years", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_object_years_year"), table_name="object_years")
    op.drop_index(op.f("ix_object_years_object_id"), table_name="object_years")
    op.drop_table("object_years")
    # ### end Alembic commands ###
