"""속성의 검증 규칙 — min·max·decimals·pattern·default·unique

지금까지는 「숫자다」 까지만 봤다. **그러면 두께가 -5mm 여도 통과하고**, 그 값은
나중에 집계에 섞여 들어가 어디서 온 것인지 아무도 못 찾는다.

Revision ID: 0007_property_rules
Revises: 0006_object_years
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0007_property_rules"
down_revision = "0006_object_years"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("property_defs", sa.Column("min_value", sa.Float(), nullable=True))
    op.add_column("property_defs", sa.Column("max_value", sa.Float(), nullable=True))
    op.add_column("property_defs", sa.Column("decimals", sa.Integer(), nullable=True))
    op.add_column("property_defs", sa.Column("pattern", sa.String(length=200), nullable=True))
    op.add_column(
        "property_defs",
        sa.Column("default_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "property_defs",
        sa.Column("unique", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("property_defs", "unique")
    op.drop_column("property_defs", "default_value")
    op.drop_column("property_defs", "pattern")
    op.drop_column("property_defs", "decimals")
    op.drop_column("property_defs", "max_value")
    op.drop_column("property_defs", "min_value")
    # ### end Alembic commands ###
