"""정의 스냅샷 — 되돌릴 자리

**감사 로그는 「누가 뭘 했나」 는 알려 주지만 되돌려 주지는 않는다.** 사람이 한 칸씩
고칠 때는 그것으로 충분했지만, 기계는 타입 20개·속성 200개를 5초에 만들고 그 실수도
같은 속도로 반영된다.

Revision ID: 0008_ontology_snapshots
Revises: 0007_property_rules
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0008_ontology_snapshots"
down_revision = "0007_property_rules"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ontology_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "taken_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_label", sa.String(length=120), server_default="", nullable=False),
        sa.Column("reason", sa.String(length=200), server_default="", nullable=False),
        sa.Column(
            "schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_ontology_snapshots_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ontology_snapshots")),
    )
    op.create_index(
        op.f("ix_ontology_snapshots_taken_at"),
        "ontology_snapshots",
        ["taken_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ontology_snapshots_taken_at"), table_name="ontology_snapshots")
    op.drop_table("ontology_snapshots")
    # ### end Alembic commands ###
