"""묶음 한 판과 **되돌릴 기록** — 백필을 통째로 되돌릴 길.

백필은 한 번에 수만 줄을 넣는다. 그 판이 틀렸을 때 되돌릴 길이 없었다 — 화면에서 객체를
하나씩 고치는 것뿐이고, 수만 줄에는 그 길이 없다. 감사 기록으로도 안 된다: 백필은
`audit="summary"` 로 돌아서 줄마다의 기록이 아예 없다(그것이 켜진 이유다).

    bundle_runs          적용한 한 판. 미리 보기는 안 남는다(아무것도 안 바뀐다)
    bundle_undo_entries  바뀐 줄마다 하나 — `before` 로 되돌리고, `after` 로 그 사이 남이
                         고쳤는지 본다

`at` 은 **`clock_timestamp()`** 다. `now()` 는 트랜잭션이 시작한 시각이라 한 트랜잭션에서
판이 여럿이면 전부 같은 시각이 되고, 그러면 최근 순서가 질의마다 달라진다(0032 · 0036 ·
0037 · 0040 과 같은 이유).

줄은 워커가 `undo_journal_ttl_days`(30일) 뒤에 비운다 — 판은 남긴다. 그래야 「그때 무엇이
들어갔나」 는 남고, 되돌릴 수 없다는 사실만 목록에서 드러난다.

Revision ID: 0043_bundle_undo
Revises: 0042_dt_history_clock
Create Date: 2026-09-30 17:09:11.712482

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0043_bundle_undo"
down_revision: Union[str, Sequence[str], None] = "0042_dt_history_clock"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bundle_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_label", sa.String(length=200), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("undone_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("undone_by_id", sa.UUID(), nullable=True),
        sa.Column("undo_note", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_bundle_runs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["undone_by_id"],
            ["users.id"],
            name=op.f("fk_bundle_runs_undone_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bundle_runs")),
    )
    op.create_index("ix_bundle_runs_at", "bundle_runs", ["at"], unique=False)
    op.create_table(
        "bundle_undo_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["bundle_runs.id"],
            name=op.f("fk_bundle_undo_entries_run_id_bundle_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bundle_undo_entries")),
    )
    op.create_index(
        "ix_bundle_undo_entries_run", "bundle_undo_entries", ["run_id", "seq"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bundle_undo_entries_run", table_name="bundle_undo_entries")
    op.drop_table("bundle_undo_entries")
    op.drop_index("ix_bundle_runs_at", table_name="bundle_runs")
    op.drop_table("bundle_runs")
    # ### end Alembic commands ###
