"""사이드바 묶음에 **상위 묶음** 한 칸 — 두 단계로 세운다.

타입이 백 개가 되면 묶음 열 개가 평평하게 늘어서고, 그때 「어디에 속한 것인가」 를 화면이
말해 주지 못한다. 계층으로 찾는 사람에게는 그 말이 지도다.

    설계 기준정보  › 기계 부품 › 부품 · 재료
                   › 장비      › 장비

**한 단계만이다.** 부모의 부모는 앱이 막는다(`group_parent_error` — 화면과 파일이 같은 규칙).
지우면 자식은 맨 위로 올라온다(`ondelete=SET NULL`) — 묶음이 사라졌다고 그 아래 타입들이
사이드바에서 함께 사라지면 안 된다.

이것은 **화면 정리**다. 타입끼리의 `parent_slug`(「개발모델은 제품이다」 · RDF 의
rdfs:subClassOf)와는 다른 계층이다.

Revision ID: 0044_group_parent
Revises: 0043_bundle_undo
Create Date: 2026-09-30 21:20:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0044_group_parent"
down_revision: Union[str, Sequence[str], None] = "0043_bundle_undo"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nav_groups", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_nav_groups_parent_id"), "nav_groups", ["parent_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_nav_groups_parent_id_nav_groups"),
        "nav_groups",
        "nav_groups",
        ["parent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_nav_groups_parent_id_nav_groups"), "nav_groups", type_="foreignkey"
    )
    op.drop_index(op.f("ix_nav_groups_parent_id"), table_name="nav_groups")
    op.drop_column("nav_groups", "parent_id")
    # ### end Alembic commands ###
