"""객체에 **사람이 고친 칸** 표시 — 다음 적재가 조용히 되돌리지 않게.

파일로 넣기는 같은 식별자면 덮는다(upsert). 그래서 원천을 다시 정제해 넣으면 사람이 화면에서
고친 값이 사라지고, 고친 사람은 그 사실을 모른다 — 몇 주 뒤 「내가 고쳤는데 다시 틀려 있다」 로
만나고, 그때 사람은 고치기를 그만둔다.

    objects.human_edits   {칸 이름: 고친 시각}

칸 이름은 고정 칸은 그대로(`label` · `status` …), 속성은 `properties.<키>`(목록 열과 같은 표기).
식별자(`key`)는 표시하지 않는다 — 파일이 그 값으로 이 객체를 찾기 때문이다.

표시는 **사람 세션**만 남긴다(화면). 기계 자격(PAT) · 워커의 적재는 안 남긴다. 적재는 표시된
칸을 비켜 가고 계획에 적는다(`human_edits="overwrite"` 면 덮고 표시를 지운다).

Revision ID: 0046_human_edits
Revises: 0045_interfaces
Create Date: 2026-10-02 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0046_human_edits"
down_revision: Union[str, Sequence[str], None] = "0045_interfaces"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "objects",
        sa.Column(
            "human_edits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("objects", "human_edits")
    # ### end Alembic commands ###
