"""데이터 소스가 **선도 받는다** — 선의 시계 한 칸.

형제 설치의 코어 창구는 객체(`/core/<타입>`)와 선(`/core/<타입>/relations`)을 따로 연다.
받는 쪽도 시계를 따로 들어야 한다 — 한 칸을 둘이 나눠 쓰면 객체를 받고 옮긴 시각이 선의
시작점이 되어 그 사이에 바뀐 선을 영영 안 받는다.

상대가 `reset: true` 를 주면(끊긴 선의 무덤이 보관 기간을 넘겼다) 이 값을 비우고 전량을 다시
받는다. 빈 쪽을 「바뀐 것 없음」 으로 읽으면 이미 끊긴 선을 영영 들고 있는다.

Revision ID: 0047_datasource_relations
Revises: 0046_human_edits
Create Date: 2026-10-02 11:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0047_datasource_relations"
down_revision: Union[str, Sequence[str], None] = "0046_human_edits"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_sources",
        sa.Column(
            "relations_since_mark", sa.String(length=64), server_default="", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_sources", "relations_since_mark")
    # ### end Alembic commands ###
