"""묶음에 **색** 한 칸 — 색은 타입이 아니라 묶음에 준다.

그래프의 색을 타입 순서로 주고 있었다. 팔레트가 열둘이라 **열셋째부터 전부 회색**이었고, 타입이
백 개가 되는 설치에서는 거의 다 회색이다(실측).

색 백 개를 만드는 것은 답이 아니다 — 사람은 그만큼을 구별하지 못한다(열둘도 많은 편이다).
그래서 색의 **뜻을 바꾼다**: 「이 타입」 이 아니라 **「어느 영역의 것인가」**. 그 영역이 묶음이고,
어느 타입인지는 라벨이 말한다. 상위 묶음이 있으면 그 색을 물려받고 농도만 달라진다 — 같은
계열로 보여야 한 영역으로 읽힌다.

이 칸은 **비워 두는 것이 기본**이다(순서대로 팔레트에서 받는다). 적으면 사내 관례를 고정한다
(「시뮬레이션은 늘 주황」).

Revision ID: 0048_group_color
Revises: 0047_datasource_relations
Create Date: 2026-10-02 14:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0048_group_color"
down_revision: Union[str, Sequence[str], None] = "0047_datasource_relations"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nav_groups",
        sa.Column("color", sa.String(length=7), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nav_groups", "color")
    # ### end Alembic commands ###
